exclude:
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.log"
  - "**/__pycache__/**"
  - "**/.venv/**"
  - "**/venv/**"
  - "**/package-lock.json"
  - "**/pnpm-lock.yaml"
