# Matrix Bridge Configuration
# Security-first configuration for RAVE autonomous dev agency

# Network configuration
host: "127.0.0.1"  # Local binding only for security
port: 9000
max_request_size: 1048576  # 1MB limit

# Matrix configuration
homeserver_url: "https://rave.local:3002/matrix"
as_token: "${MATRIX_AS_TOKEN}"  # From sops-nix secrets
hs_token: "${MATRIX_HS_TOKEN}"  # From sops-nix secrets

# GitLab OIDC configuration
gitlab_url: "https://rave.local:3002/gitlab"
oidc_client_id: "matrix-bridge"
oidc_client_secret: "${GITLAB_CLIENT_SECRET}"  # From sops-nix secrets

# Authorization configuration
allowed_groups:
  - "developers"
  - "admins" 
  - "maintainers"

# Agent control configuration
allowed_commands:
  - "start-agent"
  - "stop-agent"
  - "status-agent"
  - "list-agents"
  - "help"

allowed_agent_services:
  - "backend-architect"
  - "frontend-developer"
  - "test-writer-fixer" 
  - "ui-designer"
  - "devops-automator"
  - "api-tester"
  - "performance-benchmarker"
  - "rapid-prototyper"
  - "refactoring-specialist"

agent_service_prefix: "rave-agent-"
command_timeout: 10  # seconds

# Rate limiting configuration
rate_limit_rpm: 30  # Requests per minute
rate_limit_burst: 5  # Burst capacity

# Security configuration
max_failed_attempts: 5
lockout_duration: 300  # 5 minutes
token_leeway: 30  # JWT time validation leeway

# Logging and auditing
log_level: "INFO"
audit_log_file: "/var/log/matrix-bridge/audit.log"

# Circuit breaker configuration
circuit_breaker:
  failure_threshold: 5
  recovery_timeout: 60
  success_threshold: 3

# Cache configuration
cache_ttl: 300  # 5 minutes
max_cache_size: 1000

# Monitoring configuration
enable_metrics: true
metrics_port: 9001

# Request timeout configuration
request_timeout: 30