version: '3.8'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    user: "0:0"  # Run as root to avoid permission issues in development
    ports:
      - "8008:8008"  # HTTP port for Synapse
      - "8448:8448"  # HTTPS federation port (if needed)
    volumes:
      - "./data:/data"
    environment:
      - SYNAPSE_SERVER_NAME=localhost
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
    networks:
      - matrix-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    ports:
      - "8009:80"  # Element web client on port 8009
    volumes:
      - "./element-config.json:/app/config.json:ro"
    depends_on:
      - synapse
    networks:
      - matrix-network

  postgres-matrix:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: matrix_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - 'matrix-postgres-data:/var/lib/postgresql/data'
    networks:
      - matrix-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse -d synapse"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  matrix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  matrix-postgres-data:
    external: false